//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivosEspecificos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjetivosEspecificos()
        {
            this.ObjeEspecificosDepartamento = new HashSet<ObjeEspecificosDepartamento>();
            this.Estrategias = new HashSet<Estrategias>();
        }
    
        public int ObjetivosEspecificosId { get; set; }
        public Nullable<int> ObjetivosEstragicoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjeEspecificosDepartamento> ObjeEspecificosDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estrategias> Estrategias { get; set; }
        public virtual ObjetivosEstrategicos ObjetivosEstrategicos { get; set; }
    }
}
