//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planificacion()
        {
            this.Estrategias = new HashSet<Estrategias>();
        }
    
        public int PlanificacionId { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
        public Nullable<int> TipoPlanificacionId { get; set; }
        public Nullable<int> TipoProgramacionId { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estrategias> Estrategias { get; set; }
        public virtual Periocidad Periocidad { get; set; }
        public virtual TipoPlanificacion TipoPlanificacion { get; set; }
    }
}
