//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPOA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int id { get; set; }
        public Nullable<int> MetaID { get; set; }
        public Nullable<decimal> Planificado { get; set; }
        public Nullable<decimal> Ejecutado { get; set; }
        public Nullable<bool> eliminado { get; set; }
    
        public virtual Metas Metas { get; set; }
    }
}
